name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
